# Generated by Django 5.1.3 on 2025-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
    ]
